title: C++ for finance course materials
author:
  name: Laurence Alexander Hurst
  email: loz.hurst@gmail.com
description:>
  Materials for C++ For Finance.  Copyright 2020 Laurence Alexander Hurst.  Originally delivered at University of Birmingham.
  Based upon (but not directly derived from) work by Matthew Collins, which was in turn based upon work by Nick Webber.
  This course uses C++14 as the standard it presents. Concepts from C and older standards are presented at the end but modern practices and containers, such as references and std::array, are presented in place of out moded concepts such as pointers and C arrays.
  This a re-design of the delivery of the module, begun in week 14 of the 20-week course in academic year 2019/2020.
  The original 3 hours slot format of 1hr lecture/2hr lab session wasn't working too well for me or the students so I started this as a trial alternative approach.
